#version: "3"
include:
  - path: "docker-compose.networks.yml"
  - path: "traefik/docker-compose.traefik.yml"
  - path: "stalwart/docker-compose.stalwart.yml"
  - path: "nginx/docker-compose.nginx.yml"
