services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      #- /apps/prometheus/configs/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - /prometheus:/etc/prometheus/prometheus.yaml
      - prom_data:/prometheus
volumes:
  prom_data:
    name: prom_data
