global:
  checkNewVersion: true
  sendAnonymousUsage: false  # true by default

log:
  level: DEBUG  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: logfmt # common, json, logfmt
  #filePath: /var/log/traefik/traefik.log

accessLog:
  format: common

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false
    network: proxy
  file:
    # watch for dynamic configuration changes
    directory: /etc/traefik/dynamic_conf
    watch: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          #priority: 1000
          to: "websecure"
          scheme: "https"
  websecure:
    address: :443
    http3: {}
    http:
      tls:
        certResolver: le
  smtp:
    address: :25
    proxyProtocol:
      trustedIPs:
        - 172.20.0.2
        - 172.20.0.5
  esmtp:
    address: :465
    proxyProtocol:
      trustedIPs: 
        - 172.20.0.2
        - 172.20.0.5
  imap-ssl:
    address: :993
    proxyProtocol:
      trustedIPs: 
        - 172.20.0.2
        - 172.20.0.5
  sieve:
    address: :4190
    proxyProtocol:
      trustedIPs: 
        - 172.20.0.2
        - 172.20.0.5

# MOVED TO dynamic_conf/tls.yml but must be in static config?
certificatesResolvers:
  le:
    acme:
      tlschallenge: true
      email: "dan@denkijin.com"
      storage: "/letsencrypt/acme.json"
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
