#version: "3"
services:
  nginx:
    image: nginx:stable-alpine3.20
    depends_on: 
      - traefik
    healthcheck:
      test: ["CMD", "curl", "0.0.0.0:80"]
    labels:
      traefik.enable: true
      traefik.http.routers.nginx.service: nginx
      traefik.http.services.nginx.loadbalancer.server.port: 80
      traefik.http.routers.nginx.rule: Host(`denkijin.com`)
      traefik.http.routers.nginx.entrypoints: websecure
      traefik.http.routers.nginx.tls: true
      traefik.http.routers.nginx.tls.certresolver: le 
    networks:
      proxy:
        ipv4_address: 172.20.0.6
      srv:
    restart: unless-stopped 
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./logs:/var/log/nginx/
